/*"use client";
import { useState } from 'react';
import { useSelector } from 'react-redux';
import { useRouter } from 'next/navigation';

export default function PostJob() {
  const { user } = useSelector(state => state.auth);
  const router = useRouter();
  const [formData, setFormData] = useState({
    title: '', description: '', location: '', jobType: 'Full-time', 
    salaryRange: '', requiredSkills: '', deadline: ''
  });

  const handleSubmit = async (e) => {
    e.preventDefault();
    const newJob = {
      ...formData,
      employerId: user.id,
      companyName: user.name,
      requiredSkills: formData.requiredSkills.split(',').map(s => s.trim()),
      status: "pending", // Needs Admin Approval
      postedAt: new Date().toISOString(),
      views: 0
    };

    await fetch('http://localhost:5000/jobs', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(newJob)
    });

    alert("Job posted and awaiting admin approval!");
    router.push('/employer/dashboard');
  };

  return (
    <div className="max-w-2xl mx-auto p-8 bg-white shadow mt-10">
      <h2 className="text-2xl font-bold mb-6">Post a New Job</h2>
      <form onSubmit={handleSubmit} className="space-y-4">
        <input type="text" placeholder="Job Title" className="w-full p-2 border" required
          onChange={e => setFormData({...formData, title: e.target.value})} />
        
        <textarea placeholder="Job Description" className="w-full p-2 border h-32" required
          onChange={e => setFormData({...formData, description: e.target.value})} />
        
        <div className="grid grid-cols-2 gap-4">
          <input type="text" placeholder="Location (e.g. Remote, NY)" className="p-2 border"
            onChange={e => setFormData({...formData, location: e.target.value})} />
          <select className="p-2 border" onChange={e => setFormData({...formData, jobType: e.target.value})}>
            <option>Full-time</option>
            <option>Contract</option>
            <option>Part-time</option>
          </select>
        </div>

        <input type="text" placeholder="Skills (comma separated: React, Node)" className="w-full p-2 border"
          onChange={e => setFormData({...formData, required_skills: e.target.value})} />

        <button className="w-full bg-blue-600 text-white py-3 rounded font-bold">Submit Job Listing</button>
      </form>
    </div>
  );
}*/


"use client";
import { useState } from 'react';
import { useSelector } from 'react-redux';
import { useRouter } from 'next/navigation';

export default function PostJobPage() {
  const { user } = useSelector((state) => state.auth);
  const router = useRouter();

  // 1. Initialize state matching your schema
  const [formData, setFormData] = useState({
    title: '',
    description: '',
    location: '',
    jobType: 'Full-time',
    industry: '',
    experienceLevel: 'Entry',
    salaryRange: '',
    requiredSkills: '', // Will be converted to array on submit
    deadline: ''
  });

  const [loading, setLoading] = useState(false);

  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);

    // 2. Prepare the final object matching the "j1" structure
    const newJob = {
      // id will be auto-generated by json-server
      employerId: user?.id || "u2", // Link to logged in employer
      title: formData.title,
      description: formData.description,
      location: formData.location,
      jobType: formData.jobType,
      industry: formData.industry,
      experienceLevel: formData.experienceLevel,
      salaryRange: formData.salaryRange,
      // Convert "React, Redux" -> ["React", "Redux"]
      requiredSkills: formData.requiredSkills.split(',').map(skill => skill.trim()),
      deadline: formData.deadline,
      postedAt: new Date().toISOString(),
      status: "approved", // or "pending" if you want admin to approve
      views: 0
    };

    try {
      const res = await fetch('http://localhost:5000/jobs', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(newJob)
      });

      if (res.ok) {
        alert("Job Posted Successfully!");
        router.push('/jobs'); // Redirect to job listings
      }
    } catch (error) {
      alert("Error posting job");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="max-w-3xl mx-auto p-8 bg-white shadow-lg mt-10 rounded-xl border border-gray-100">
      <h2 className="text-3xl font-bold mb-8 text-blue-900">Post a New Opening</h2>
      
      <form onSubmit={handleSubmit} className="grid grid-cols-1 md:grid-cols-2 gap-6">
        
        {/* Title */}
        <div className="md:col-span-2">
          <label className="block text-sm font-semibold text-gray-700 mb-1">Job Title</label>
          <input type="text" required placeholder="e.g. Senior React Developer"
            className="w-full p-3 border rounded-lg outline-none focus:ring-2 focus:ring-blue-500 text-black"
            onChange={e => setFormData({...formData, title: e.target.value})} />
        </div>

        {/* Industry & Location */}
        <div>
          <label className="block text-sm font-semibold text-gray-700 mb-1">Industry</label>
          <input type="text" required placeholder="e.g. IT, Finance"
            className="w-full p-3 border rounded-lg text-black"
            onChange={e => setFormData({...formData, industry: e.target.value})} />
        </div>
        <div>
          <label className="block text-sm font-semibold text-gray-700 mb-1">Location</label>
          <input type="text" required placeholder="e.g. Remote, Chennai"
            className="w-full p-3 border rounded-lg text-black"
            onChange={e => setFormData({...formData, location: e.target.value})} />
        </div>

        {/* Type & Experience */}
        <div>
          <label className="block text-sm font-semibold text-gray-700 mb-1">Job Type</label>
          <select className="w-full p-3 border rounded-lg bg-white text-black"
            onChange={e => setFormData({...formData, jobType: e.target.value})}>
            <option>Full-time</option>
            <option>Part-time</option>
            <option>Contract</option>
            <option>Internship</option>
          </select>
        </div>
        <div>
          <label className="block text-sm font-semibold text-gray-700 mb-1">Experience Level</label>
          <select className="w-full p-3 border rounded-lg bg-white text-black"
            onChange={e => setFormData({...formData, experienceLevel: e.target.value})}>
            <option>Entry</option>
            <option>Intermediate</option>
            <option>Senior</option>
            <option>Expert</option>
          </select>
        </div>

        {/* Salary & Deadline */}
        <div>
          <label className="block text-sm font-semibold text-gray-700 mb-1">Salary Range</label>
          <input type="text" placeholder="e.g. 80k - 120k"
            className="w-full p-3 border rounded-lg text-black"
            onChange={e => setFormData({...formData, salaryRange: e.target.value})} />
        </div>
        <div>
          <label className="block text-sm font-semibold text-gray-700 mb-1">Application Deadline</label>
          <input type="date" required
            className="w-full p-3 border rounded-lg text-black"
            onChange={e => setFormData({...formData, deadline: e.target.value})} />
        </div>

        {/* Skills */}
        <div className="md:col-span-2">
          <label className="block text-sm font-semibold text-gray-700 mb-1">Required Skills (Comma separated)</label>
          <input type="text" required placeholder="React, Redux, TypeScript"
            className="w-full p-3 border rounded-lg text-black"
            onChange={e => setFormData({...formData, requiredSkills: e.target.value})} />
          <p className="text-xs text-gray-400 mt-1">Separate each skill with a comma.</p>
        </div>

        {/* Description */}
        <div className="md:col-span-2">
          <label className="block text-sm font-semibold text-gray-700 mb-1">Job Description</label>
          <textarea required rows="4" placeholder="Detailed job requirements and responsibilities..."
            className="w-full p-3 border rounded-lg text-black"
            onChange={e => setFormData({...formData, description: e.target.value})} />
        </div>

        <button disabled={loading} className="md:col-span-2 bg-blue-600 text-white py-4 rounded-lg font-bold hover:bg-blue-700 transition shadow-lg">
          {loading ? "Posting..." : "Publish Job Listing"}
        </button>
      </form>
    </div>
  );
}